### ISSUE TITLE
Docker task in yaml based build cannot find Azure Resource Manager Endpoint

### ISSUE THREAD

**Issue by bzuu** [Microsoft/vsts-agent#1420]
I created a .vsts-ci.yml file with the following contents:

```yaml
steps:
- task: Docker@0
  inputs:
    azureSubscription: 'My Azure Subscription'
    azureContainerRegistry: 'myregistry'
    action: 'Build an image'
    dockerFile: '**/Dockerfile'
    imageName: 'hello-world:$(Build.BuildId)'
- task: Docker@0
  inputs:
    azureSubscription: 'My Azure Subscription'
    azureContainerRegistry: 'myregistry'
    action: 'Push an image'
    imageName: 'hello-world:$(Build.BuildId)'
```

However when I run the build it fails immediately with the following error:

`Step input azureSubscription references endpoint My Azure Subscription which could not be found. The service endpoint does not exist or has not been authorized for use.`

I am using VSTS as well as the latest build agent (2.129.1), although it seems the build agent is not even touched at this point.

When creating a non-yaml build definition using the same values all works just fine.
