### ISSUE TITLE
Support matrix conditions

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vsts-agent#1501]
We have setup a build in VS Code which takes advantage of a build matrix to build for two different platforms. We also use the `conditions` directive to conditionally build such a phase.

https://github.com/Microsoft/vscode/blob/master/build/tfs/product-build.yml

```yml
phases:
- phase: Windows
  condition: eq(variables['VSCODE_BUILD_WIN32'], 'true')
  queue:
    name: Hosted VS2017
    parallel: 2
    matrix:
      x64:
        VSCODE_ARCH: x64
      ia32:
        VSCODE_ARCH: ia32
```

Is it possible to support conditions per matrix combination? The current condition checks `VSCODE_BUILD_WIN32` for the `true` value. I'd like to get that behaviour per matrix combination and check both `VSCODE_BUILD_WIN32_X64` and `VSCODE_BUILD_WIN32_IA32` variables to conditionally build `x64` and `ia32` respectively.

**Comment by ericsciple** [comment]
For your specific scenario, since you only have two values in the matrix, a workaround would be to specify two phases instead.

We are in the process of rolling out a new feature, where sections of your process can pull in reusable template files. Here is a real world [example](https://github.com/Microsoft/vsts-tasks/pull/6951/files). The docs for the feature are [here](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-templates.md).

That would enable you to easily define two phases, without duplicating the list of steps twice. You would put the steps in a separate file, and then reference the same file from each phase. We expect to be able to turn on the feature for all scale units, later this month.

We are also working on providing more context for template expresions. We want to be able to enable something like this:
```yaml
phases:
- ${{ if or(eq(variables['VSCODE_BUILD_WIN32_X64'], 'true'), eq(variables['VSCODE_BUILD_WIN32_IA32'], 'true')) }}:
  - phase: Windows
    queue:
      name: Hosted VS2017
      parallel: 2
      matrix:
        ${{ if eq(variables['VSCODE_BUILD_WIN32_X64'], 'true') }}:
          x64:
            VSCODE_ARCH: x64
        ${{ if eq(variables['VSCODE_BUILD_WIN32_IA32'], 'true') }}:
          ia32:
            VSCODE_ARCH: ia32
```
