### ISSUE TITLE
Caanot include * for trigger in yaml build

### ISSUE THREAD

**Issue by AceHack** [Microsoft/vsts-agent#1531]
I get the following error

(Line: 6, Col: 7, Idx: 105) - (Line: 6, Col: 8, Idx: 106): While scanning an anchor or alias, did not find expected alphabetic or numeric character.

```
trigger:
  branches:
    include:
    - *
    exclude:
    - master
```
