### ISSUE TITLE
Yaml Builds missing documentation on how to configure `Batch changes while a build is in progress`

### ISSUE THREAD

**Issue by Ziugy** [Microsoft/vsts-agent#1549]
Hi! I found the Yaml triggers page to change branch filters here: https://github.com/Microsoft/vsts-agent/blob/5be21f6185f2c4340550c04cf0dcf426cd0d3474/docs/preview/yamlgettingstarted-triggers.md

I'm unable to find any information on how to set the batch changes through Yaml. Currently working around this by selecting **Defined here** as the **Settings source** radial option.

**Comment by ericsciple** [comment]
we're working on it now. we work in 3 week sprints, so it should start rolling out across our production environments in a few weeks

**Comment by ericsciple** [comment]
This is rolling out with last sprint's deployment. It's deployed for most accounts now. The rest will roll out next week. The syntax is like this:

```yaml
trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
    exclude:
    - releases/old*
```
