### ISSUE TITLE
Template parameter can't be used in arguments parameter

### ISSUE THREAD

**Issue by AceHack** [Microsoft/vsts-agent#1576]
```
parameters:
  buildConfiguration: Release
  restoreProjects: '**/*.csproj'
  projects: 'Source/*.csproj'
  tests: 'Test/*.csproj'
  nugetConfigPath: NuGet.config

steps:
- task: DotNetCoreCLI@2
  displayName: Build Projects
  inputs:
    projects: ${{ parameters.projects }}
    arguments: '--no-restore -c ${{ parameters.buildConfiguration }}'
```

`${{ parameters.buildConfiguration }}` is not recognized in this context, it tries to use the literal `${{ parameters.buildConfiguration }}` instead of `Release`

**Comment by AceHack** [comment]
@ericsciple I did almost your workaround but I needed it in multiple steps so I added this pre-step.

```
- powershell: 'Write-Host "##vso[task.setvariable variable=BuildConfiguration]$($env:BuildConfiguration)"'
  displayName: Setup Environment Variables
  env:
    BuildConfiguration: ${{ parameters.buildConfiguration }}
  ignoreLASTEXITCODE: false
  errorActionPreference: Stop
  failOnStderr: true
```

I used powershell and $env:BuildConfiguration to create a lasting variable that works on both linux and windows.  If you know a better cross-platform way to do this, I would really like to see it.


The format command is okay but I'm not thrilled about it.  I don't really see the harm in `${{ }}` and I've not seen any documentation on runtime expressions `$[ ]` so I don't know how they are used.  If you really don't want to allow for `${{ }}` a very useful built-in task or setting on the template would be a way to easily convert all template parameters to variables.

Thanks.
