### ISSUE TITLE
_core.yml (Line: 7, Col: 19): A template expression is not allowed in this context

### ISSUE THREAD

**Issue by AceHack** [Microsoft/vsts-agent#1581]
Please allow template parameters to reference other template parameters, see below.

```
parameters:
  buildConfiguration: Release
  buildReleasePackage: false
  nugetConfigPath: NuGet.config
  restoreProjects: '**/*.csproj'
  projects: 'Source/*.csproj'
  packagesToPack: ${{ parameters.projects }}
  tests: 'Test/**/*.csproj'
```

**Comment by ericsciple** [comment]
This is an interesting problem. By default do you really want to pack all projects?

I'm also curious if you have come across this same limitation for any other scenarios.

**Comment by AceHack** [comment]
This is a contrived example, what I really want is to be able to reference once earlier parameter in a later parameter.  I do this from time to time in PowerShell scripts.


When you say come across the same limitation for any other scenarios, you run into this limitation whenever you try to access parameter values inside of another parameter.


Thanks.

**Comment by ericsciple** [comment]
I'm thinking about adding a coalesce function and solving this problem a different way.

```yaml
parameters:
  projects: **/*.csproj
  projectsToPack: '' # empty implies all
  pack: true

steps:
- task: build[...]
- ${{ if eq(true, parameters.pack) }}
  - task: pack[...]
    inputs:
      projects: ${{ coalesce( parameters.projectsToPack, parameters.projects ) }}
```

I think this would be a reasonable alternate solution. PowerShell is very expressive. I'm not sure I want to go that far with template parameters. Let me know what you think. I'm also interested in concrete template scenarios.

I'm going to go ahead and close the issue here, since this isn't an open issue in the sense of a bug that we're tracking. The dialog here is useful.
