### ISSUE TITLE
Cannot call git tag/push in yaml build

### ISSUE THREAD

**Issue by AceHack** [Microsoft/vsts-agent#1582]
```
  - powershell: |
      Write-Host "git tag $env:tag"
      git tag $env:tag
      Write-Host "git push origin $env:tag"
      git push origin $env:tag
    displayName: Git Tag
    workingDirectory: $(Build.SourcesDirectory)
    env:
      tag: '$(PACKAGE_VERSION)'
      SYSTEM_ACCESSTOKEN: $(system.accesstoken)
    ignoreLASTEXITCODE: false
    errorActionPreference: Stop
    failOnStderr: true
```

This command freezes forever no matter what permissions I add.  I'm able to call the same command from the UI build and it works without any issues, this is only a problem in yaml builds.

**Comment by TingluoHuang** [comment]
@AceHack you didn't feed in credential to git, it freezes since it is trying to prompt for credential.

**Comment by AceHack** [comment]
@TingluoHuang Please elaborate.  How would I do that?  My understanding was OAuth token is always there in yaml builds.

**Comment by TingluoHuang** [comment]
@AceHack it's available in ENV for yaml build for now, we are working on repository checkout option for preserver git credential, for now, i guess you need to run
`git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" tag MyTag`

**Comment by AceHack** [comment]
so that command shows up already in the build under the automatic step "Get sources"

> 2018-05-25T22:35:00.9346747Z ##[command]git -c http.extraheader="AUTHORIZATION: bearer ***" fetch --tags --prune --progress --no-recurse-submodules origin

**Comment by AceHack** [comment]
I tried several different combinations with the following command

```
- powershell: |
    Write-Host "git tag $env:tag"
    git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" tag $env:tag
    Write-Host "git push origin $env:tag"
    git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" push origin $env:tag
  displayName: Git Tag
  workingDirectory: $(Build.SourcesDirectory)
  env:
    tag: '$(PACKAGE_VERSION)'
    SYSTEM_ACCESSTOKEN: $(system.accesstoken)
  ignoreLASTEXITCODE: false
  errorActionPreference: Stop
  failOnStderr: true
```

trying the token on the tag line, push line, both.

Just the tag line, still freezes
Either just the push line or both tag line and push line fail with:

> To https://xxx.visualstudio.com/xxx/_git/SampleProject


That's it, no more error message, just that.

**Comment by bryanmacfarlane** [comment]
Did you give permission to the service account?  It doesn't have push permissions by default.

https://docs.microsoft.com/en-us/vsts/build-release/actions/scripts/git-commands?view=vsts

**Comment by AceHack** [comment]
Yes, I did that to get git tag working in UI build.  UI builds can git tag this repo with no issues.

**Comment by AceHack** [comment]
@ericsciple I don't expect the git version is the issue since it works fine with UI builds but here is the results.

git version 2.14.3.windows.1

**Comment by TingluoHuang** [comment]
@AceHack can you share your log file?

**Comment by AceHack** [comment]
> ******************************************************************************
> Starting: Git Tag
> ******************************************************************************
> ==============================================================================
> Task         : PowerShell
> Description  : This is an early preview. Run a PowerShell script on Windows, macOS, or Linux.
> Version      : 2.129.0
> Author       : Microsoft Corporation
> Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
> ==============================================================================
> Generating script.
> "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'c:\agent_b\_work\_temp\bfc03e29-cf01-436d-a174-1a2fc271af62.ps1'"
> git version 2.14.3.windows.1
> git tag 2.5.20-ci.2018.149.1.master
> git push origin 2.5.20-ci.2018.149.1.master
> ******************************************************************************
> Starting: Post Job Cleanup
> ******************************************************************************
> Cleaning any cached credential from repository: Platform.DotNet (Git)
> To https://itron.visualstudio.com/CloudServicesPlatform/_git/Platform.DotNet
> ******************************************************************************
> Finishing: Git Tag
> ******************************************************************************

**Comment by AceHack** [comment]
Also for reference here is the exact command I ran:

```
- powershell: |
    git --version
    Write-Host "git tag $env:tag"
    git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" tag $env:tag
    Write-Host "git push origin $env:tag"
    git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" push origin $env:tag
  displayName: Git Tag
  workingDirectory: $(Build.SourcesDirectory)
  env:
    tag: '$(PACKAGE_VERSION)'
    SYSTEM_ACCESSTOKEN: $(system.accesstoken)
  ignoreLASTEXITCODE: false
  errorActionPreference: Stop
  failOnStderr: true
```


And the line


To https://itron.visualstudio.com/CloudServicesPlatform/_git/Platform.DotNet

Shows up in red, everything is is normal color.

**Comment by TingluoHuang** [comment]
@AceHack instead of `Write-Host "git tag $env:tag"`, can you change it to `Write-Host "git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" tag $env:tag"`

**Comment by TingluoHuang** [comment]
@AceHack BTW, git use STDERR to report progress information, so i don't think you want to `failOnStderr: true`, instead, you should check return code of each git command.

**Comment by AceHack** [comment]
@TingluoHuang FYI, I've included my command as I did previously and you can see I'm already doing what you suggested.

```
- powershell: |
    git --version
    Write-Host "git tag $env:tag"
    **git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" tag $env:tag**
    Write-Host "git push origin $env:tag"
    git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" push origin $env:tag
  displayName: Git Tag
  workingDirectory: $(Build.SourcesDirectory)
  env:
    tag: '$(PACKAGE_VERSION)'
    SYSTEM_ACCESSTOKEN: $(system.accesstoken)
  ignoreLASTEXITCODE: false
  errorActionPreference: Stop
  failOnStderr: true
```


Also as I've stated earlier I've tried every combination of adding `-c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN"`, only on the tag, only on the push, on both the tag and push and on neither the tag nor push.  They all fail in some way.


I will try turning off failOnStderr and report back.

Thanks.

**Comment by AceHack** [comment]
`failOnStderr: false` fixed the issue

**Comment by vicentemg** [comment]
> ```
>   - powershell: |
>       Write-Host "git tag $env:tag"
>       git tag $env:tag
>       Write-Host "git push origin $env:tag"
>       git push origin $env:tag
>     displayName: Git Tag
>     workingDirectory: $(Build.SourcesDirectory)
>     env:
>       tag: '$(PACKAGE_VERSION)'
>       SYSTEM_ACCESSTOKEN: $(system.accesstoken)
>     ignoreLASTEXITCODE: false
>     errorActionPreference: Stop
>     failOnStderr: true
> ```
> This command freezes forever no matter what permissions I add. I'm able to call the same command from the UI build and it works without any issues, this is only a problem in yaml builds.

Hi Aaron how did you do that from the UI Build?
I want to tag my commits when the build and all test are ok. 
But I just got create a tag but not push it

**Comment by dilv0055** [comment]
Hi, i still the same issue only with git push origin <tag_name>. Every thing else like git pull, git push, git tag, git fetch are working great. I'm using Azure DevOps Build pipeline, Powershell task(version 2.0) and git version is git version 2.17.1.windows.2. 

Issue: Pipeline waiting for longtime.

**Comment by gentledepp** [comment]
For the sake of completeness:
We had a similar issue with git failing. Here is how re resolved it! 🎉 

1.  Our build agent had the standard permissionset, but as we enabled **custom policies** on our branch (such as disallowing direct pushes without a PR), the agent needed additional permissiosn:
- *bypass policies when pushing* 
- and *bypass policies when completing pull requests*

2. Then, we did not have to pass the bearer token using  `git -c ....` as described above. Rather, we just had to add a task `checkout` with `persistCretentials:true`.

3. Finally, there was one more important step: We had a powershell inline script which was essentially calling 
```powershell
git tag $(GitVersion.NuGetVersion)
git push --tags
```
this **ALWAYS** failed with the error code 1 as it is described above in this thread.
The **only** way we could get rid of this error was to split those comands into **two separate powershell scripts**

So for you guys, here is the essential parts of our yaml file:

```yaml

# run on PRs and whenever a feature branch is pushed
trigger:
- master
- feature/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Sample.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# NOTE: You need tos pecify 'persistCredentials:true' to allow your build agent to has access to git commands for pull/tag/push
# see https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml
- checkout: self
  persistCredentials: true
  clean: true

# create semantic version
- task: GitVersion@5
  inputs:
    runtime: 'full'

# ...
# ... run all your crazy build stuff here 
# ...

# tag the current branch with the version number
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git tag $(GitVersion.NuGetVersion)
      Write-Host "Successfully created tag $(GitVersion.NuGetVersion)" 

# push created tag to origin
# NOTE: you need to set 'persistCredentials: true' in the checkout task. Otherwise git will fail with error code 1.
# NOTE: You cannot run both "git tag xyz" AND "git push --task" in the same powershell command. If you do, git will fail with error code 1
# NOTE: IF you get an error from this git command, make sure, that your build user has the required permissions!
#       In our case, the build agent needs the additional permissions for "bypass policies when pushing" and "bypass policies when completing pull requests"
#       because we have a custom policy in place. (See: https://opti-q.visualstudio.com/<your_project_name>/_settings/repositories)
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git push --tags
      Write-Host "Successfully pushed tag $(GitVersion.NuGetVersion) to origin"      


```
