### ISSUE TITLE
Tag exclusion in yaml trigger definition

### ISSUE THREAD

**Issue by plang85** [Microsoft/vsts-agent#1649]
## Have you tried trouble shooting?
yes

## Agent Version and Platform
2.134.2, CentOS 7

## VSTS Type and Version
VisualStudio.com

## What's not working?
I have a yaml definition
```
trigger:
  branches:
    include:
    - master
    exclude:
    - tags/*
    - refs/tags/*

phases:
  - phase: Test
    queue:
      name: ResSimTesting
      demands:
        - Agent.OS -equals Linux

    steps:
    - task: Bash@3
      displayName: bash me some
      inputs:
        targetType: 'inline'
        script: |
          echo hello
```
which runs in CI mode by default (ie leaving trigger settings in vsts ui alone). It fails to ignore the tag and try to build it

![tag error](https://ixdev.blob.core.windows.net/cache/trigger-tag-0.png)
 
however if I whitelist master in the UI this doesn't happen

![tag error](https://ixdev.blob.core.windows.net/cache/trigger-tag-1.png)
 
Am I missing something here?

**Comment by TingluoHuang** [comment]
@plang85 can you make it work with a pure designer build definition?

**Comment by TingluoHuang** [comment]
i am trying to figure out whether this is YAML problem or it's a generic limitation for the build system.

**Comment by plang85** [comment]
If I define the whole thing in the UI and have the branch filter set to master it works as expected (ignores any pushed tags)

**Comment by TingluoHuang** [comment]
@plang85 do you means if your YAML looks like:
```
trigger:
  branches:
    include:
    - master
```
it will also trigger on tag?

**Comment by ericsciple** [comment]
I hit an exception when attempting to repro this: `Expected a Commit, but objectId e0e48f6a41f99e979256f27a9177c791e8dabb9c resolved to a Tag`

I'll dig in more later today.

**Comment by plang85** [comment]
Somewhat related
https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/13326927-trigger-build-when-pushing-tag-to-git

**Comment by ericsciple** [comment]
@plang85 when you tried, did you get a similar error that I did? i'm fixing that, but want to confirm whether you are running into a different issue.

**Comment by plang85** [comment]
Thanks for looking into this. I get the same error, yes. However I would like to exclude any tags to be build, and I was not able to find the right yaml syntax for than.

**Comment by ericsciple** [comment]
There were bugs around tags. I checked in fixes which are rolling out with the current deployment. It will take a couple weeks to reach all accounts. The problem was annotated tags were causing failed builds to be created, whether the file excluded tags or not (error occurred while attempting to load the yaml file)

**Comment by nexussays** [comment]
Really appreciate the explanation @ericsciple, thanks!

**Comment by ericsciple** [comment]
Closing the issue here. The deployment has reached most accounts, and will roll out to the rest sometime next week.

**Comment by domoritz** [comment]
I have the opposite problem. When I use triggers for tagged commits, they don't get triggered

```
trigger:
  branches:
    include:
      - refs/heads/master
      - refs/tags/*
```

**Comment by EzraBrooks** [comment]
Having the same issue as above, although I'm not manually defining triggers. Before a few weeks ago, it was defaulting to building on tags just as it was defaulting to building on branch commits.

**Comment by ericsciple** [comment]
@domoritz are you using an Azure Repo or GitHub? Are you using lightweight tags or annotated tags? Note, when the tag is pushed, the triggers defined by the yaml file **in that commit** is what is used to determine whether to trigger a build.

**Comment by ericsciple** [comment]
@EzraBrooks there were inconsistencies and bugs with triggers on tags. The expected behavior going forward is, you must list refs/tags/* (or specific tag patterns) if you want tags to trigger.

**Comment by EzraBrooks** [comment]
Thanks for the info, I'll try it out.

**Comment by domoritz** [comment]
I use GitHub with normal git tags. The tank file is in the tagged commit.

**Comment by EzraBrooks** [comment]
With identical configuration to @domoritz, I'm not getting builds on tags either.

**Comment by domoritz** [comment]
@chrisrpatterson helped me in https://github.com/vega/ts-json-schema-generator/issues/49

**Comment by solvingj** [comment]
@ericsciple based on your comment, I believe this document is no longer correct.  Can you confirm I'm interpreting it correctly?

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#tags

> If you don't specify any tag triggers, the default is as if you wrote:
```
trigger:
  tags:
    include:
    - *
```
