### ISSUE TITLE
Exported YAML not valid - "While parsing a block mapping, did not find expected key."

### ISSUE THREAD

**Issue by simonvane** [Microsoft/vsts-agent#1677]
## Have you tried trouble shooting?
yes

## Agent Version and Platform
Hosted VS2017

## VSTS Type and Version
VisualStudio.com 

## What's not working?
When build definition is exported using "View YAML" the following was included:

```
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: |  
     **/Project1.csproj
     **/Project2.csproj
     **/Project3.csproj
      feedsToUse: config
      nugetConfigPath: NuGet.config
```

Using it to create a build resulted in the error "While parsing a block mapping, did not find expected key." Changing the indenting to the following resolved the problem.

```
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: |  
        **/Project1.csproj
        **/Project2.csproj
        **/Project3.csproj
      feedsToUse: config
      nugetConfigPath: NuGet.config
```

Exported YAML should be valid and a clearer error message would be helpful.
