### ISSUE TITLE
Templated YAML build pipeline failing to authorize resources

### ISSUE THREAD

**Issue by 4c74356b41** [Microsoft/vsts-agent#1681]
## Agent Version and Platform
VSTS Hosted 2017 and Linux Preview

## VSTS Type and Version
VSTS; http://duckbot.visualstudio.com

## What's not working?
![image](https://user-images.githubusercontent.com/16194643/42410450-6394d952-81f2-11e8-9272-baea7b299950.png)
Yaml templated definition cannot authorize docker container registry (Azure PaaS resource)

## Additional information

I'm using the Hosted Linux Preview agent and Hosted VS 2017 (2 phases)
I'm using GitHub as source control
I'm doing tests on develop and master branches, and observe similar behavior.
My .yml file is not in the root folder (under ./vsts/*.yml)
It's working fine via the Build Definition UI (so not using yaml)
It's working fine if it's not using templates (so everything in 1 yaml).

Sample yaml:
```
name: $(GITVERSION_NuGetVersion)
resources:
- repo: self
  fetchDepth: 1
  clean: true

phases:
- template: vsts/buildApplication.yml

- template: vsts/buildContainer.yml
  parameters:
    appName: 'webApplication'
    appFolder: 'UI'
```

in the buildContainer.yml I have this:
```
azureSubscription: yyy
azureContainerRegistry: '{"loginServer":"xxx.azurecr.io", "id":"/subscriptions/guid/resourceGroups/name/providers/Microsoft.ContainerRegistry/registries/name"}'
```

i saw [that document](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-authz.md) and it helped me with this issue when everything was in the one yaml definition, but not with templates. funny enough if I edit the working definition (so the one with resources approved already) to use the templated approach - it breaks.
