### ISSUE TITLE
Question: Reuse of parameters in YAML templates

### ISSUE THREAD

**Issue by BiribiriJaNai** [Microsoft/vsts-agent#1686]
Hi, 

I'm trying to reuse parameters in a template. When using them as conditions, it works fine.
When trying to reuse them as tasks' parameters, it doesn't work so well.

**Example:** I would like to reuse `parameters.os` as an input parameter for the `PublishTestResults` task and display either **Linux Tests** or **Windows Tests** in the build summary, using the `testRunTitle` input of the task.
I've tried with `${{ parameters.os }}`, `$(parameters.os)` without success.

![image](https://user-images.githubusercontent.com/29836717/42448485-952cf6f2-837d-11e8-8437-b2c36f9126e4.png)

Is this possible? Am I missing something?
Thanks!

My **.vsts-ci.yml file**
```
phases:

# Linux
- phase: build_all_linux
  displayName: Build all tasks (Linux)
  queue: 
    name: Azure
    demands:
    - agent.OS -equals linux
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      os: Linux

# Windows
- phase: build_all_windows
  displayName: Build all tasks (Windows)
  queue: 
    name: Azure
    demands:
    - agent.OS -equals Windows_NT
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      os: Windows
```
My **ci/build-all-steps.yml**
```
parameters:
  os: ''

steps:
# some 
# tasks 
# here

# publish tests results
- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFiles: '**/test-results.xml'
    mergeTestResults: true
    # this is where I'm stuck, expecting 'Linux Tests' or 'Windows Tests'
    testRunTitle: ${{ parameters.os }} Tests

```

**Comment by ericsciple** [comment]
```yaml
testRunTitle: ${{ format('{0} Tests', parameters.testTitle }}
```

**Comment by ericsciple** [comment]
I added this example to the docs https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-templateexpressions.md#functions

**Comment by BiribiriJaNai** [comment]
Thanks @TingluoHuang  and @ericsciple.
Worked like a charm!

**Comment by ericsciple** [comment]
@BiribiriJaNai thanks for the confirmation.

Also note, we would like to enable the more intuitive form:

```yaml
testRunTitle: ${{ parameters.testTitle }} Tests
```

...we just havent gotten to it yet.

**Comment by HermanCordes** [comment]
@ericsciple The example you've provided on 9th of July causes a 'format not closed' error. When adding a closing parenthesis it will work:

`testRunTitle: ${{ format('{0} Tests', parameters.testTitle }})`

**Comment by BiribiriJaNai** [comment]
@HermanCordes , I think your closing parenthesis is misplaced. It should be right after `testTitle`.
And I just realized that the the sample provided by @ericsciple  is missing its closing parenthesis.
What worked for me : `testRunTitle: ${{ format('{0} Tests', parameters.testTitle) }}`

**Comment by HermanCordes** [comment]
@BiribiriJaNai You're right, apparently I made a copy+paste error. Thanks for the correction.

**Comment by ericsciple** [comment]
@BiribiriJaNai when the next sprint rolls out, you will be able to do this:

```yaml
parameters:
  os: ''
steps:
- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
     testRunTitle: ${{ parameters.os }} Tests
```

It will start rolling out after next week, and will take about three weeks to finish rolling out to all accounts.
