### ISSUE TITLE
vsts agent queue gets stuck on and off

### ISSUE THREAD

**Issue by melezhik** [Microsoft/vsts-agent#1696]
## Have you tried trouble shooting?
Yes

## Agent Version and Platform
2.131.0, 2.134.0, 2.136.1

OS of the machine running the agent? Windows

## VSTS Type and Version
VisualStudio.com

## What's not working?

This is very annoying bug for me. Steps to reproduce:

1. install private agent, name agent-01, run it as service ( network service account ) 

2. create build definition in YAML, running forcefully on agent-01:

```
resources:

- repo: self

queue:
  name: Q123
  timeoutInMinutes: 20
  demands:
  - Agent.name -equals agent-01

steps:
```

3. run your builds and be happy, everything looks good so far

4. In one or two weeks begin to notice that my builds gets stuck in queue Q123 with message:

"all agents are disabled" ( or something like that ... don't remember exact phrasing  )

5. go to machine where agent is installed, stop the agent, run it manually in foreground: 

```
$ run.cmd
```

6. noticing that the queue is being proceeded, the stuck builds get running 

7. stop agent, run it as the service, back to normal operation cycle, the bug is fixed.

Best

Alexey
