### ISSUE TITLE
Artifactory deployer task does not work for YAML build 

### ISSUE THREAD

**Issue by melezhik** [Microsoft/vsts-agent#1710]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
2.136.1

OS of the machine running the agent? 

Windows 

## VSTS Type and Version
VisualStudio.com

## What's not working?

Build does not even start with error:

```
Step input artifactoryEndpointName references endpoint could not be found. The service endpoint does not exist or has not been authorized for use.

```

Here is my build definition:

```
queue:
  name: Q1

steps:
- task: JFrog.jfrog-artifactory.jfrog-artifactory-deployer-build-task.JFrogArtifactoryDeployer@2
  displayName: JFrogArtifactoryDeployer 
  inputs:
    artifactoryEndpointName: 'Artifactory-Prod'
    targetRepo: 'nuget-local'

```

If run GUI equivalent of the same build it succeeds. I confirm that artifactory endpoint does exist and set correctly.
