### ISSUE TITLE
YAML Calculate value for task input using conditions

### ISSUE THREAD

**Issue by t3mi** [Microsoft/vsts-agent#1727]
## Have you tried trouble shooting?
Couldn't queue the build

## Agent Version and Platform
Version of your agent?
2.136.1

OS of the machine running the agent? 
CentOS 7 x64 7.5

## VSTS Type and Version
VSTS

## What's not working?
According to [templateexpressions](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-templateexpressions.md) there is a possibility to use task condition for the templates. I've tried to use next value for one of the task input _${{ and(not(parameters.force), not(parameters.override)) }}_ and it wasn't calculated properly. Limiting value to just one function _${{ not(parameters.force) }}_ throws the same error. I want to have task enabled/disabled depending on the value of two parameters. Is it possible?

Error in VSTS while trying to queue a build:
build.package.yml (Line: 13, Col: 14): Unexpected type: 'System.Boolean',build.package.yml (Line: 13, Col: 14): Expected a Boolean value. Actual value: ''

```
# .vsts-ci.yml
name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.rr)
queue: PrivatePool
steps:
  - template: build.package.yml
    parameters:
      force: true
```

```
# build.package.yml
parameters:
  force: false
  override: false

steps:
  - checkout: self
    clean: true

  - task: DownloadBuildArtifacts@0
    displayName: Download Build Artifacts
    condition: and(succeeded(), in(variables['build.reason'], 'Manual', 'Schedule'))
    continueOnError: true
    enabled: ${{ and(not(parameters.force), not(parameters.override)) }}
    inputs:
      buildType: specific
      downloadType: specific
```

**Comment by ericsciple** [comment]
Thanks I was able to repro the bug. Here is a workaround:

```yaml
# build.package.yml
parameters:
  force: false
  override: false

steps:
  - checkout: self
    clean: true
  - ${{ if and(ne(parameters.force, 'false'), ne(parameters.override, 'false')) }}
    - task: DownloadBuildArtifacts@0
      displayName: Download Build Artifacts
      condition: and(succeeded(), in(variables['build.reason'], 'Manual', 'Schedule'))
      continueOnError: true
      inputs:
        buildType: specific
        downloadType: specific
```
