### ISSUE TITLE
"not equal" agents demands in yaml build definition 

### ISSUE THREAD

**Issue by melezhik** [Microsoft/vsts-agent#1740]
Hi vsts devs! I have found in documentation and wonder if it possible to have a "not equal" agent demands in yaml build definitions?

```

resources:

- repo: self

queue:
  name: Q1
  demands:
   - Param1 -nequals Value1

```

Best

Alexey
