### ISSUE TITLE
Cannot mount volumes when running Docker task inside self-hosted agent running on GKE

### ISSUE THREAD

**Issue by ColeSiegelTR** [Microsoft/vsts-agent#3584]
I set up a self-hosted ADO agent which runs inside a GKE container. When I tried to transfer my existing docker-compose build from the Microsoft agent pool to my own self hosted agent, the docker-compose fails to mount the volume. I receive errors saying that I cannot create directories since the file system is read-only.

ADO pipeline task:
```
  - task: DockerCompose@0
    displayName: Run Tests
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'xxx'
      dockerComposeFile: 'src/docker-compose.yml'
      dockerComposeFileArgs: |
        VOLUME=$(Build.ArtifactStagingDirectory)
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'up'
```
Docker Compose:

```
version: '3.3'
services:
    system_tests:
        volumes:
            - '${VOLUME}:/output'
        image: ubuntu:latest
```
Build error:

```
##[error]ERROR: for system_tests  Cannot start service system_tests: error while creating mount source path '/azp/_work/2/a': mkdir /azp: read-only file system
```

Any suggestions how to troubleshoot this? I need the volume mount to `$(Build.ArtifactStagingDirectory)` so that I can publish files from the docker run as ADO artifacts. It's not clear to me if the instructions about docker in docker are relevant to my use case https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#use-docker-within-a-docker-container or how I could approach this solution https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#mounting-volumes-using-docker-within-a-docker-container using kubernetes.

GKE version - `1.20.10-gke.301`
ADO agent version - `2.185.1`
